"use client";

// MorningBriefing — top-of-scratchpad AI-narrated daily brief.
//
// Calls provider.briefMe() with the user's overdue/today/soon tasks
// and recent note bodies. The model produces a short markdown
// summary that gets rendered with hand-rolled minimal markdown
// (CommentBody-style — no external dep). Auto-refresh every hour
// while the page is open; manual refresh button for impatience.
//
// Empty-state copy never fires the API — saves a round-trip when
// the user has no tasks at all.

import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Sparkles, Loader2, RefreshCw, AlertTriangle } from "lucide-react";
import { getAiProvider } from "@/lib/ai";
import type { BriefContext } from "@/lib/ai/types";
import type { DailyBrief } from "@/lib/notes";
import { listNotes } from "@/lib/notes";

interface Props {
  orgId: string;
  userId: string;
  brief: DailyBrief;
}

export default function MorningBriefing({ orgId, userId, brief }: Props) {
  const provider = useMemo(() => getAiProvider(), []);
  const [text, setText] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [stale, setStale] = useState(false);

  const isEmpty = brief.totals.total === 0;

  const buildCtx = useCallback(async (): Promise<BriefContext> => {
    // Grab the 5 most recent notes the actor authored for theme detection.
    const recent = await listNotes({ orgId, actorUserId: userId, limit: 5 });
    return {
      overdue: brief.overdue.map((t) => ({ body: t.task.body, dueAt: t.task.dueAt, noteCreatedAt: t.note.createdAt })),
      today:   brief.today.map((t)   => ({ body: t.task.body, dueAt: t.task.dueAt, noteCreatedAt: t.note.createdAt })),
      soon:    brief.soon.map((t)    => ({ body: t.task.body, dueAt: t.task.dueAt, noteCreatedAt: t.note.createdAt })),
      recentNoteBodies: recent.map((n) => n.body),
      today_iso: new Date().toISOString().slice(0, 10),
    };
  }, [brief, orgId, userId]);

  const run = useCallback(async () => {
    if (isEmpty) { setText(null); return; }
    setBusy(true); setError(null); setStale(false);
    try {
      const ctx = await buildCtx();
      const result = await provider.briefMe(ctx);
      setText(result);
    } catch (e) {
      setError((e as Error).message || "Couldn't generate brief.");
    } finally {
      setBusy(false);
    }
  }, [buildCtx, provider, isEmpty]);

  // Auto-run once when brief is ready. Re-run when brief totals change.
  const briefKey = `${brief.totals.overdue}-${brief.totals.today}-${brief.totals.soon}-${brief.totals.later}-${brief.totals.noDate}`;
  useEffect(() => { void run(); /* eslint-disable-line react-hooks/exhaustive-deps */ }, [briefKey]);

  // Mark stale after an hour to nudge a refresh.
  useEffect(() => {
    if (!text) return;
    const t = setTimeout(() => setStale(true), 60 * 60 * 1000);
    return () => clearTimeout(t);
  }, [text]);

  if (isEmpty) return null;

  return (
    <div className="bg-gradient-to-br from-amber-50 via-white to-violet-50 rounded-2xl border border-amber-200/60 shadow-sm overflow-hidden">
      <div className="px-4 py-2.5 bg-gradient-to-r from-amber-100/60 to-violet-100/40 border-b border-amber-200/40 flex items-center gap-2">
        <Sparkles className="w-4 h-4 text-amber-600" />
        <div className="text-xs font-black text-slate-900 uppercase tracking-widest">Morning briefing</div>
        <span
          className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider border ${
            provider.isReal
              ? "bg-emerald-50 text-emerald-700 border-emerald-300"
              : "bg-slate-100 text-slate-600 border-slate-300"
          }`}
          title={provider.isReal ? `Generated by ${provider.name}` : "Local heuristic — connect a real AI provider for a narrated brief."}
        >
          <span className={`w-1.5 h-1.5 rounded-full ${provider.isReal ? "bg-emerald-500 animate-pulse" : "bg-slate-400"}`} />
          {provider.isReal ? "AI" : "Mock"}
        </span>
        {stale && <span className="text-[10px] text-slate-500 italic">may be stale</span>}
        <button
          onClick={run}
          disabled={busy}
          className="ml-auto inline-flex items-center gap-1 px-2 py-1 rounded-md hover:bg-white/60 text-[11px] font-bold text-slate-700 disabled:opacity-50"
          title="Re-generate briefing"
        >
          {busy ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
          {busy ? "Thinking…" : "Refresh"}
        </button>
      </div>
      <div className="px-4 py-3 text-sm text-slate-800 leading-relaxed">
        {busy && !text && (
          <div className="text-xs text-slate-500 italic inline-flex items-center gap-1.5">
            <Loader2 className="w-3 h-3 animate-spin" /> Reading your scratchpad…
          </div>
        )}
        {error && (
          <div className="text-xs text-rose-700 inline-flex items-center gap-1.5">
            <AlertTriangle className="w-3.5 h-3.5" /> {error}
          </div>
        )}
        {text && <MarkdownBlock text={text} />}
      </div>
    </div>
  );
}

// Minimal markdown — bold (`**x**`), italic (`*x*`), inline code, list items.
// Same shape as components/requests/CommentBody so callers stay consistent.
function MarkdownBlock({ text }: { text: string }) {
  const lines = text.split("\n");
  return (
    <div className="space-y-1">
      {lines.map((line, i) => {
        if (!line.trim()) return <div key={i} className="h-2" />;
        const isList = /^\s*[-*]\s+/.test(line);
        const body = line.replace(/^\s*[-*]\s+/, "");
        return (
          <div key={i} className={isList ? "flex items-start gap-2" : ""}>
            {isList && <span className="text-amber-500 mt-0.5">•</span>}
            <span className="flex-1" dangerouslySetInnerHTML={{ __html: inlineMd(body) }} />
          </div>
        );
      })}
    </div>
  );
}

function inlineMd(s: string): string {
  // Escape first — same approach as CommentBody.
  const esc = s
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  return esc
    .replace(/\*\*([^*]+)\*\*/g, '<b class="font-bold text-slate-900">$1</b>')
    .replace(/\*([^*\n]+)\*/g, '<i class="italic">$1</i>')
    .replace(/`([^`]+)`/g, '<code class="font-mono bg-slate-100 px-1 rounded text-xs">$1</code>');
}
