-- 20260623_document_shares.sql
--
-- Time-limited public share links for documents. Generated by an org
-- member; resolvable without auth from a tokenized URL.
--
-- Surface model: the rendered URL is /share/<token>. The /share route
-- reads the token, looks up an unrevoked + unexpired row, generates a
-- presigned download URL for the current version's storage path, and
-- delivers it. Each access bumps access_count and access_last_at for
-- the audit trail.

CREATE TABLE IF NOT EXISTS document_shares (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token TEXT NOT NULL UNIQUE,                  -- url-safe random token
  org_id UUID NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  created_by UUID NOT NULL,
  created_by_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ,                       -- null = no expiry (rare; admin sets)
  revoked_at TIMESTAMPTZ,
  revoked_by UUID,
  note TEXT,                                    -- optional human note ("for John at the vendor")
  -- Audit
  access_count INTEGER DEFAULT 0,
  access_last_at TIMESTAMPTZ,
  access_last_ip TEXT
);

CREATE INDEX IF NOT EXISTS document_shares_token_idx ON document_shares(token);
CREATE INDEX IF NOT EXISTS document_shares_doc_idx ON document_shares(document_id, created_at DESC);
CREATE INDEX IF NOT EXISTS document_shares_org_idx ON document_shares(org_id, created_at DESC);

ALTER TABLE document_shares ENABLE ROW LEVEL SECURITY;

-- Anyone in the org can create / list / revoke shares on docs in that org
DROP POLICY IF EXISTS document_shares_org_member ON document_shares;
CREATE POLICY document_shares_org_member ON document_shares FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM org_members
      WHERE org_members.org_id = document_shares.org_id
        AND org_members.uid = auth.uid()
        AND org_members.status = 'active'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM org_members
      WHERE org_members.org_id = document_shares.org_id
        AND org_members.uid = auth.uid()
        AND org_members.status = 'active'
    )
  );

COMMENT ON TABLE document_shares IS
  'Time-limited public share links. Tokens are url-safe and unguessable. Resolved by /share/<token> server route which generates a presigned download URL on each access.';
