-- Document-control Phase 3 — close the permissive-RLS family.
--
-- Three CRITICALs whose fix is at the database, and which the sequencing file
-- says must land before any per-table RLS fix or those fixes are decorative:
--
--   · DRLS-1 — the own-row hardening on document_acknowledgments and
--     document_review_signoffs (20260828/20260830) is VOID, because a second
--     permissive `FOR ALL` policy generated by the 20260819 loop under the
--     LONG name `<table>_member_all` was never dropped (the hand-written
--     migrations drop only the SHORT `doc_ack_member_all` / `doc_review_
--     signoff_member_all` names). PERMISSIVE policies OR together, so the long
--     ones alone grant every UPDATE/DELETE the own-row policies were written to
--     deny. Any active member could PATCH another engineer's ack row or DELETE
--     a review roster.
--
--   · DCK-2 — checkout_sessions RLS is `FOR ALL USING` only, and the release
--     rail is a BEFORE UPDATE trigger keyed on a status change. So DELETE
--     bypasses the rail entirely (no DELETE trigger, no DELETE policy), and a
--     non-status edit — outcome / outcome_note / outcome_ref, or user_id — on
--     another user's session is unguarded (a forged walkdown attestation).
--
--   · DCK-3 — documents RLS is `FOR ALL USING` only, so any active member can
--     PATCH documents.checked_out_by / current_lock_id directly and seize or
--     clear another user's lock, past the checkout_sessions rail (which never
--     sees a write to documents).
--
-- DCK-2/DCK-3 are fixed with BEFORE UPDATE/DELETE trigger GUARDS rather than
-- by tightening the permissive policies, because the app performs legitimate
-- CROSS-USER writes those policies must keep allowing — e.g. linking every
-- co-holder's active session to a shared episode (episode_id), and passing a
-- lock to the heir on the holder's way out. The guards restrict only the
-- AUTHORITY columns, so those benign cross-user writes are untouched.
--
-- ⚠ APPLIED BY HAND (DEC-30). Idempotent; safe to re-run.

BEGIN;

-- ── DRLS-1: drop the leftover permissive policies ───────────────────────────
-- After this, the only policies on these two tables are the 20260828/20260830
-- per-op set (select / insert / update / delete), which is the intended model.
DROP POLICY IF EXISTS document_acknowledgments_member_all ON document_acknowledgments;
DROP POLICY IF EXISTS document_review_signoffs_member_all ON document_review_signoffs;

-- ── DCK-2: checkout_sessions — guard DELETE and outcome/identity edits ───────
-- Complements the existing enforce_checkout_release_guard (status transitions);
-- this covers the two holes that guard cannot: DELETE, and non-status edits to
-- another user's session. auth.uid() IS NULL → a service-role / cron write
-- (no JWT), which is trusted.
CREATE OR REPLACE FUNCTION enforce_checkout_session_guard()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN COALESCE(NEW, OLD); END IF;

  IF TG_OP = 'DELETE' THEN
    -- Deleting another user's session would end their checkout past the
    -- release rail (which only fires on UPDATE). Controller-only.
    IF OLD.user_id::text <> auth.uid()::text
       AND NOT org_capability_allows(OLD.org_id, 'checkout.force_release', auth.uid()) THEN
      RAISE EXCEPTION 'You are not allowed to delete another user''s checkout session.'
        USING ERRCODE = 'check_violation';
    END IF;
    RETURN OLD;
  END IF;

  -- UPDATE: the walkdown OUTCOME and the session's identity are the owner's to
  -- write. (episode_id / status linking on co-holders' rows is deliberately
  -- NOT guarded here — status is covered by the release rail, and episode_id
  -- is a benign shared-episode link.)
  IF OLD.user_id::text <> auth.uid()::text
     AND NOT org_capability_allows(OLD.org_id, 'checkout.force_release', auth.uid())
     AND ( NEW.user_id      IS DISTINCT FROM OLD.user_id
        OR NEW.outcome       IS DISTINCT FROM OLD.outcome
        OR NEW.outcome_note  IS DISTINCT FROM OLD.outcome_note
        OR NEW.outcome_ref   IS DISTINCT FROM OLD.outcome_ref ) THEN
    RAISE EXCEPTION 'You are not allowed to change another user''s checkout session.'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_checkout_session_guard ON checkout_sessions;
CREATE TRIGGER trg_checkout_session_guard
BEFORE UPDATE OR DELETE ON checkout_sessions
FOR EACH ROW EXECUTE FUNCTION enforce_checkout_session_guard();

-- ── DCK-3: documents — guard the lock authority columns ─────────────────────
-- A change to checked_out_by / current_lock_id is allowed only when the doc is
-- currently FREE (claim), the caller is the CURRENT holder (transfer to an
-- heir, or clear on last-out), or the caller holds checkout.force_release.
-- This permits exactly the transitions lib/checkoutEpisodes.ts performs (its
-- CAS filters are `checked_out_by IS NULL OR = self`, and the heir transfer
-- runs as the departing holder) and blocks a bare seize/clear of someone
-- else's lock.
CREATE OR REPLACE FUNCTION enforce_document_lock_guard()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN NEW; END IF;
  IF NEW.checked_out_by IS DISTINCT FROM OLD.checked_out_by
     OR NEW.current_lock_id IS DISTINCT FROM OLD.current_lock_id THEN
    IF OLD.checked_out_by IS NOT NULL
       AND OLD.checked_out_by::text <> auth.uid()::text
       AND NOT org_capability_allows(OLD.org_id, 'checkout.force_release', auth.uid()) THEN
      RAISE EXCEPTION 'You are not allowed to change the checkout lock held by another user.'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_document_lock_guard ON documents;
CREATE TRIGGER trg_document_lock_guard
BEFORE UPDATE ON documents
FOR EACH ROW EXECUTE FUNCTION enforce_document_lock_guard();

COMMIT;

-- ── Verification (read-only) ────────────────────────────────────────────────
-- (a) The two tables now carry ONLY the intended per-op policies — expect the
--     leftover member_all names to be GONE (zero rows):
SELECT tablename, policyname
FROM pg_policies
WHERE tablename IN ('document_acknowledgments', 'document_review_signoffs')
  AND policyname LIKE '%member_all%';

-- (b) Both guards are installed (expect true / true):
SELECT 'checkout_session guard installed' AS check,
       EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_checkout_session_guard' AND NOT tgisinternal) AS ok
UNION ALL
SELECT 'document lock guard installed',
       EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_document_lock_guard' AND NOT tgisinternal);
